dependencies:
- name: demo-conference-agenda
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.37
- name: demo-conference-c4p
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.66
- name: demo-conference-site
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.44
- name: demo-conference-email
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.18

